export type SpeciesCategory = 'Bird' | 'Mammal' | 'Reptile / Amphibian';

export interface Species {
  name: string;
  scientificName: string;
  category: SpeciesCategory;
  description: string;
  wikipediaUrl: string;
  imageUrl: string;
}

export const speciesList: Species[] = [
  // Birds
  {
    name: 'American Robin',
    scientificName: 'Turdus migratorius',
    category: 'Bird',
    description: 'A common North American songbird with a reddish-orange breast and cheerful morning song.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/American_robin',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/American_robin_%2871307%29.jpg/330px-American_robin_%2871307%29.jpg',
  },
  {
    name: 'Canada Goose',
    scientificName: 'Branta canadensis',
    category: 'Bird',
    description: 'A large wild goose native to North America with a distinctive black head and neck.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Canada_goose',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Canada_goose.jpg/330px-Canada_goose.jpg',
  },
  {
    name: 'Mallard Duck',
    scientificName: 'Anas platyrhynchos',
    category: 'Bird',
    description: 'The most common and widespread wild duck, with males showing iridescent green heads.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Mallard',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Anas_platyrhynchos_male_female_quadrat.jpg/330px-Anas_platyrhynchos_male_female_quadrat.jpg',
  },
  {
    name: 'Northern Flicker',
    scientificName: 'Colaptes auratus',
    category: 'Bird',
    description: 'A medium-sized woodpecker that often forages on the ground for ants and beetles.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Northern_flicker',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Northern_yellow-shafted_flicker_male_%2833737%29_%28cropped%29.jpg/330px-Northern_yellow-shafted_flicker_male_%2833737%29_%28cropped%29.jpg',
  },
  {
    name: 'Red-winged Blackbird',
    scientificName: 'Agelaius phoeniceus',
    category: 'Bird',
    description: 'A common bird of wetlands and fields, males display bright red shoulder patches.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Red-winged_blackbird',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Red-Winged_Blackbird.png/330px-Red-Winged_Blackbird.png',
  },
  {
    name: 'Yellow Warbler',
    scientificName: 'Setophaga petechia',
    category: 'Bird',
    description: 'A small, bright yellow songbird commonly found in riparian habitats and gardens.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Yellow_warbler',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Yellow_Warbler_at_the_Pool%2C_Central_Park%2C_New_York_City.jpg/330px-Yellow_Warbler_at_the_Pool%2C_Central_Park%2C_New_York_City.jpg',
  },
  {
    name: 'House Sparrow',
    scientificName: 'Passer domesticus',
    category: 'Bird',
    description: 'A small, chunky bird commonly found in urban and suburban areas near human habitation.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/House_sparrow',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/House_sparrow_male_in_Prospect_Park_%2853532%29.jpg/330px-House_sparrow_male_in_Prospect_Park_%2853532%29.jpg',
  },
  {
    name: 'European Starling',
    scientificName: 'Sturnus vulgaris',
    category: 'Bird',
    description: 'An iridescent black bird introduced to North America, known for its mimicry and murmurations.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Common_starling',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Common_starling_%28Sturnus_vulgaris%29_breeding_male_Marken.jpg/330px-Common_starling_%28Sturnus_vulgaris%29_breeding_male_Marken.jpg',
  },
  {
    name: 'Black-capped Chickadee',
    scientificName: 'Poecile atricapillus',
    category: 'Bird',
    description: 'A tiny, curious bird with a distinctive black cap and bib, and a cheerful chick-a-dee call.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Black-capped_chickadee',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Poecile-atricapilla-001.jpg/330px-Poecile-atricapilla-001.jpg',
  },
  {
    name: 'Mountain Chickadee',
    scientificName: 'Poecile gambeli',
    category: 'Bird',
    description: 'A small songbird of western coniferous forests with a distinctive white eyebrow stripe.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Mountain_chickadee',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Mountain_Chickadee_Sandia_Mountains.jpg/330px-Mountain_Chickadee_Sandia_Mountains.jpg',
  },
  {
    name: 'Dark-eyed Junco',
    scientificName: 'Junco hyemalis',
    category: 'Bird',
    description: 'A common sparrow with dark gray or brown plumage and a pale belly, often seen at feeders.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Dark-eyed_junco',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Junco_hyemalis_hyemalis_CT1_%28cropped%29.jpg/330px-Junco_hyemalis_hyemalis_CT1_%28cropped%29.jpg',
  },
  {
    name: 'White-crowned Sparrow',
    scientificName: 'Zonotrichia leucophrys',
    category: 'Bird',
    description: 'A large sparrow with striking black and white stripes on its head.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/White-crowned_sparrow',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/White-crowned-Sparrow.jpg/330px-White-crowned-Sparrow.jpg',
  },
  {
    name: 'Song Sparrow',
    scientificName: 'Melospiza melodia',
    category: 'Bird',
    description: 'A melodious and highly variable sparrow found in a wide range of habitats.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Song_sparrow',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Song_sparrow_in_Prospect_Park_%2893031%29.jpg/330px-Song_sparrow_in_Prospect_Park_%2893031%29.jpg',
  },
  {
    name: 'Western Meadowlark',
    scientificName: 'Sturnella neglecta',
    category: 'Bird',
    description: 'A medium-sized bird with a distinctive yellow chest and a flute-like song.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Western_meadowlark',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Sturnella_neglecta_GNP_02.jpg/330px-Sturnella_neglecta_GNP_02.jpg',
  },
  {
    name: 'American Goldfinch',
    scientificName: 'Spinus tristis',
    category: 'Bird',
    description: 'A small, bright yellow finch that breeds later in the summer than most songbirds.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/American_goldfinch',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Carduelis_tristis_-Michigan%2C_USA_-male-8.jpg/330px-Carduelis_tristis_-Michigan%2C_USA_-male-8.jpg',
  },
  {
    name: 'Pine Siskin',
    scientificName: 'Spinus pinus',
    category: 'Bird',
    description: 'A small, streaked finch with a sharp, pointed bill, often found in coniferous forests.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Pine_siskin',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Carduelis_pinus_CT7.jpg/330px-Carduelis_pinus_CT7.jpg',
  },
  {
    name: 'Bald Eagle',
    scientificName: 'Haliaeetus leucocephalus',
    category: 'Bird',
    description: 'A powerful bird of prey and national symbol of the United States with a white head and tail.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Bald_eagle',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Bald_eagle_about_to_fly_in_Alaska_%282016%29.jpg/330px-Bald_eagle_about_to_fly_in_Alaska_%282016%29.jpg',
  },
  {
    name: 'Osprey',
    scientificName: 'Pandion haliaetus',
    category: 'Bird',
    description: 'A fish-eating raptor with reversible outer toes and a distinctive dark eye stripe.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Osprey',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Osprey_Perched_Snag_Heislerville.jpg/330px-Osprey_Perched_Snag_Heislerville.jpg',
  },
  {
    name: 'Red-tailed Hawk',
    scientificName: 'Buteo jamaicensis',
    category: 'Bird',
    description: 'A broad-winged hawk commonly seen soaring over open fields and along highways.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Red-tailed_hawk',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Red-tailed_Hawk_%2845812546121%29.jpg/330px-Red-tailed_Hawk_%2845812546121%29.jpg',
  },
  {
    name: "Cooper's Hawk",
    scientificName: 'Accipiter cooperii',
    category: 'Bird',
    description: 'A medium-sized hawk with a long tail and short wings, often found in woodlands.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cooper%27s_hawk',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Accipiter_cooperii_m_Sam_Smith_Toronto3.jpg/330px-Accipiter_cooperii_m_Sam_Smith_Toronto3.jpg',
  },
  {
    name: 'Great Blue Heron',
    scientificName: 'Ardea herodias',
    category: 'Bird',
    description: 'The largest heron in North America, often seen wading in shallow water hunting for fish.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Great_blue_heron',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/GreatBlueHeronInARiver.jpg/330px-GreatBlueHeronInARiver.jpg',
  },
  {
    name: 'Common Raven',
    scientificName: 'Corvus corax',
    category: 'Bird',
    description: 'A large, all-black bird known for its intelligence, complex vocalizations, and aerial acrobatics.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Common_raven',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Corvus_corax.jpg/330px-Corvus_corax.jpg',
  },
  {
    name: 'American Crow',
    scientificName: 'Corvus brachyrhynchos',
    category: 'Bird',
    description: 'A large, all-black passerine bird that is highly adaptable and often seen in urban areas.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/American_crow',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Corvus-brachyrhynchos-001.jpg/330px-Corvus-brachyrhynchos-001.jpg',
  },

  // Mammals
  {
    name: 'Mule Deer',
    scientificName: 'Odocoileus hemionus',
    category: 'Mammal',
    description: 'A deer indigenous to western North America with large, mule-like ears.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Mule_deer',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Mule_buck_elk_creek_m_myatt_%285489214303%29.jpg/330px-Mule_buck_elk_creek_m_myatt_%285489214303%29.jpg',
  },
  {
    name: 'White-tailed Deer',
    scientificName: 'Odocoileus virginianus',
    category: 'Mammal',
    description: 'The most widely distributed wild ungulate in North America, named for its white tail underside.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/White-tailed_deer',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/White-tailed_deer.jpg/330px-White-tailed_deer.jpg',
  },
  {
    name: 'Coyote',
    scientificName: 'Canis latrans',
    category: 'Mammal',
    description: 'A canine native to North America, smaller than a wolf and highly adaptable to human environments.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Coyote',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/2009-Coyote-Yosemite.jpg/330px-2009-Coyote-Yosemite.jpg',
  },
  {
    name: 'Black Bear',
    scientificName: 'Ursus americanus',
    category: 'Mammal',
    description: 'North America\'s most common bear species, typically black but can also be brown or cinnamon.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/American_black_bear',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/01_Schwarzb%C3%A4r.jpg/330px-01_Schwarzb%C3%A4r.jpg',
  },
  {
    name: 'Grizzly Bear',
    scientificName: 'Ursus arctos horribilis',
    category: 'Mammal',
    description: 'A large subspecies of brown bear found in inland North America, known for its distinctive shoulder hump.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Grizzly_bear',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/GrizzlyBearJeanBeaufort.jpg/330px-GrizzlyBearJeanBeaufort.jpg',
  },
  {
    name: 'Raccoon',
    scientificName: 'Procyon lotor',
    category: 'Mammal',
    description: 'A medium-sized mammal with a distinctive black mask and ringed tail, known for its dexterous front paws.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Raccoon',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Raccoon_in_Central_Park_%2835264%29.jpg/330px-Raccoon_in_Central_Park_%2835264%29.jpg',
  },
  {
    name: 'Red Fox',
    scientificName: 'Vulpes vulpes',
    category: 'Mammal',
    description: 'The largest of the true foxes, with reddish fur, a white underbelly, and a bushy tail.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Red_fox',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog_%28cropped%29.jpg/330px-Portrait_of_a_red_fox_in_Rautas_fj%C3%A4llurskog_%28cropped%29.jpg',
  },
  {
    name: 'Bobcat',
    scientificName: 'Lynx rufus',
    category: 'Mammal',
    description: 'A medium-sized North American wild cat with a short tail, tufted ears, and spotted coat.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Bobcat',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Bobcat_at_Columbus_Zoo_Boo.jpg/330px-Bobcat_at_Columbus_Zoo_Boo.jpg',
  },
  {
    name: 'Lynx',
    scientificName: 'Lynx canadensis',
    category: 'Mammal',
    description: 'A medium-sized wild cat with large, snowshoe-like paws and a short, black-tipped tail.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Canada_lynx',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Canada_lynx_by_Michael_Zahra_%28cropped%29.jpg/330px-Canada_lynx_by_Michael_Zahra_%28cropped%29.jpg',
  },
  {
    name: 'Snowshoe Hare',
    scientificName: 'Lepus americanus',
    category: 'Mammal',
    description: 'A medium-sized hare with large hind feet and fur that turns white in winter.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Snowshoe_hare',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Lepus_americanus_5459_cropped.jpg/330px-Lepus_americanus_5459_cropped.jpg',
  },
  {
    name: "Nuttall's Cottontail",
    scientificName: 'Sylvilagus nuttallii',
    category: 'Mammal',
    description: 'A small rabbit native to western North America with a short, white, cottony tail.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Nuttall%27s_cottontail',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Sylvilagus_audubonii_2.jpg/330px-Sylvilagus_audubonii_2.jpg',
  },
  {
    name: 'Beaver',
    scientificName: 'Castor canadensis',
    category: 'Mammal',
    description: 'North America\'s largest rodent, famous for building dams, lodges, and canals.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/North_American_beaver',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/American_Beaver.jpg/330px-American_Beaver.jpg',
  },
  {
    name: 'Muskrat',
    scientificName: 'Ondatra zibethicus',
    category: 'Mammal',
    description: 'A semi-aquatic rodent found in wetlands, named for the musky odor it produces.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Muskrat',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Muskrat_swimming_Ottawa.jpg/330px-Muskrat_swimming_Ottawa.jpg',
  },
  {
    name: 'Chipmunk',
    scientificName: 'Tamias spp.',
    category: 'Mammal',
    description: 'A small, striped ground squirrel often seen scurrying through forests and gardens.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Chipmunk',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Chipmunk_with_stuffed_cheeks_in_Prospect_Park_%2805980%29.jpg/330px-Chipmunk_with_stuffed_cheeks_in_Prospect_Park_%2805980%29.jpg',
  },
  {
    name: 'Ground Squirrel',
    scientificName: 'Urocitellus spp.',
    category: 'Mammal',
    description: 'A ground-dwelling rodent that lives in burrows and is often seen standing upright on its hind legs.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Ground_squirrel',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Yer_sincab%C4%B1.jpg/330px-Yer_sincab%C4%B1.jpg',
  },
  {
    name: 'River Otter',
    scientificName: 'Lontra canadensis',
    category: 'Mammal',
    description: 'A playful, semi-aquatic mammal with a streamlined body and dense, water-repellent fur.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/North_American_river_otter',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Northern_River_Otter_on_Seedskadee_NWR_%2822802102984%29.jpg/330px-Northern_River_Otter_on_Seedskadee_NWR_%2822802102984%29.jpg',
  },

  // Reptiles and Amphibians
  {
    name: 'Painted Turtle',
    scientificName: 'Chrysemys picta',
    category: 'Reptile / Amphibian',
    description: 'A colorful freshwater turtle with red and yellow markings on its shell and skin.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Painted_turtle',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Painted_turtle_%28Chrysemys_picta%29_Madden_Haag.jpg/330px-Painted_turtle_%28Chrysemys_picta%29_Madden_Haag.jpg',
  },
  {
    name: 'Western Painted Turtle',
    scientificName: 'Chrysemys picta bellii',
    category: 'Reptile / Amphibian',
    description: 'The largest subspecies of painted turtle, found in ponds and slow-moving waters of the West.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Painted_turtle',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Painted_turtle_%28Chrysemys_picta%29_Madden_Haag.jpg/330px-Painted_turtle_%28Chrysemys_picta%29_Madden_Haag.jpg',
  },
  {
    name: 'Western Toad',
    scientificName: 'Anaxyrus boreas',
    category: 'Reptile / Amphibian',
    description: 'A large toad with a light stripe down its back, found in a variety of habitats from forest to meadows.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Western_toad',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Bufo_boreas_5629.JPG/330px-Bufo_boreas_5629.JPG',
  },
  {
    name: 'Pacific Tree Frog',
    scientificName: 'Pseudacris regilla',
    category: 'Reptile / Amphibian',
    description: 'A small, green or brown frog known for its loud, two-part call often heard at dusk.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Pacific_tree_frog',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Pacific_Tree_Frog_%28Pseudacris_regilla%29_3.JPG/330px-Pacific_Tree_Frog_%28Pseudacris_regilla%29_3.JPG',
  },
  {
    name: 'Long-toed Salamander',
    scientificName: 'Ambystoma macrodactylum',
    category: 'Reptile / Amphibian',
    description: 'A mole salamander with notably long toes and a dorsal stripe in yellow, green, or tan.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Long-toed_salamander',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Ambystoma_macrodactylum_sigillatum%2C_Plumas_County%2C_CA.jpg/330px-Ambystoma_macrodactylum_sigillatum%2C_Plumas_County%2C_CA.jpg',
  },
  {
    name: 'Common Garter Snake',
    scientificName: 'Thamnophis sirtalis',
    category: 'Reptile / Amphibian',
    description: 'A harmless, common snake with three longitudinal stripes running down its body.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Common_garter_snake',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Thamnophis_sirtalis_sirtalis_Wooster.jpg/330px-Thamnophis_sirtalis_sirtalis_Wooster.jpg',
  },
  {
    name: 'Western Terrestrial Garter Snake',
    scientificName: 'Thamnophis elegans',
    category: 'Reptile / Amphibian',
    description: 'A variable garter snake found near water in western North America.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Western_terrestrial_garter_snake',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Coast_Garter_Snake.jpg/330px-Coast_Garter_Snake.jpg',
  },
  {
    name: 'Garter Snake',
    scientificName: 'Thamnophis sirtalis',
    category: 'Reptile / Amphibian',
    description: 'A common, harmless snake with distinctive stripes, often found in gardens and near water.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Common_garter_snake',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Thamnophis_sirtalis_sirtalis_Wooster.jpg/330px-Thamnophis_sirtalis_sirtalis_Wooster.jpg',
  },
  {
    name: 'Rubber Boa',
    scientificName: 'Charina bottae',
    category: 'Reptile / Amphibian',
    description: 'A small, docile boa with smooth, shiny scales and a blunt tail that resembles its head.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Rubber_boa',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Charina_bottae_190641848.jpg/330px-Charina_bottae_190641848.jpg',
  },
  {
    name: 'Racer (Yellow-bellied Racer)',
    scientificName: 'Coluber constrictor mormon',
    category: 'Reptile / Amphibian',
    description: 'A fast, slender snake that is olive-brown above with a yellow underside.',
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Western_yellow-bellied_racer',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Coluber_constrictor_mormon_--_closeup_of_face%2C_side.jpg/330px-Coluber_constrictor_mormon_--_closeup_of_face%2C_side.jpg',
  },
];

export const notSureSpecies: Species = {
  name: 'Not Sure / Other',
  scientificName: '',
  category: 'Bird',
  description: 'Select this option if you are uncertain of the species identification. Accurate reporting is more important than guessing.',
  wikipediaUrl: '',
  imageUrl: '',
};

export function getSpeciesByCategory(category: SpeciesCategory): Species[] {
  const filtered = speciesList.filter((s) => s.category === category);
  return [...filtered, { ...notSureSpecies, category }];
}

export function findSpecies(name: string): Species | undefined {
  if (name === notSureSpecies.name) return notSureSpecies;
  return speciesList.find((s) => s.name === name);
}

export function searchSpecies(query: string, category?: SpeciesCategory): Species[] {
  const list = category ? getSpeciesByCategory(category) : [...speciesList, notSureSpecies];
  const lower = query.toLowerCase();
  return list.filter((s) => s.name.toLowerCase().includes(lower));
}
